-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Nov 16, 2020 at 11:46 AM
-- Server version: 5.7.32-0ubuntu0.18.04.1
-- PHP Version: 7.4.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `RealDynamic`
--

-- --------------------------------------------------------

--
-- Table structure for table `images`
--

CREATE TABLE `images` (
  `id` int(11) NOT NULL,
  `titulo` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `imagenes` varchar(70) COLLATE utf8mb4_unicode_ci NOT NULL,
  `descripcion` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `tipo` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `images`
--

INSERT INTO `images` (`id`, `titulo`, `imagenes`, `descripcion`, `tipo`) VALUES
(1, 'Flores Sobre Blanco', 'gallery-item-01.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria1'),
(2, 'Zapatos Sobre Pelo', 'gallery-item-02.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria1'),
(3, 'Flamingo', 'gallery-item-03.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria1'),
(4, 'Hamaca', 'gallery-item-04.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria1'),
(5, 'Reflexion', 'gallery-item-05.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria1'),
(6, 'Moderno', 'gallery-item-06.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria1'),
(7, 'Metal Sobre Frio', 'gallery-item-07.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria1'),
(8, 'Su Icidio', 'gallery-item-08.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria1'),
(9, 'Old York', 'gallery-item-09.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria1'),
(10, 'Olas', 'gallery-item-10.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria1'),
(11, 'Ofi Time', 'gallery-item-11.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria1'),
(12, 'Salud Mental', 'gallery-item-12.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria1'),
(13, 'Flores Sobre Blanco', 'gallery-item-01.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria2'),
(14, 'Zapatos Sobre Pelo', 'gallery-item-02.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria2'),
(15, 'Flamingo', 'gallery-item-03.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria2'),
(16, 'Hamaca', 'gallery-item-04.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria2'),
(17, 'Reflexion', 'gallery-item-05.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria2'),
(18, 'Moderno', 'gallery-item-06.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria2'),
(19, 'Metal Sobre Frio', 'gallery-item-07.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria2'),
(20, 'Su Icidio', 'gallery-item-08.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria2'),
(21, 'Old York', 'gallery-item-09.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria2'),
(22, 'Olas', 'gallery-item-10.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria2'),
(23, 'Ofi Time', 'gallery-item-11.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria2'),
(24, 'Salud Mental', 'gallery-item-12.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria2'),
(25, 'Flores Sobre Blanco', 'gallery-item-01.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria3'),
(26, 'Zapatos Sobre Pelo', 'gallery-item-02.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria3'),
(27, 'Flamingo', 'gallery-item-03.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria3'),
(28, 'Hamaca', 'gallery-item-04.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria3'),
(29, 'Reflexion', 'gallery-item-05.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria3'),
(30, 'Moderno', 'gallery-item-06.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria3'),
(31, 'Metal Sobre Frio', 'gallery-item-07.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria3'),
(32, 'Su Icidio', 'gallery-item-08.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria3'),
(33, 'Old York', 'gallery-item-09.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria3'),
(34, 'Olas', 'gallery-item-10.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria3'),
(35, 'Ofi Time', 'gallery-item-11.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria3'),
(36, 'Salud Mental', 'gallery-item-12.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus neque eu aliquam ultricies. Mauris justo tortor, vehicula sit amet aliquam eget, vulputate non felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent in nunc turpis. Suspendisse varius, ex non volutpat convallis, dolor sem egestas eros, sit amet varius ligula lacus in orci.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut pretium in nulla non pellentesque. In mattis mi sit amet risus fermentum posuere. Nullam vitae leo dapibus, semper urna at, faucibus urna. Curabitur aliquam ante ligula, eu scelerisque eros commodo eget. Proin feugiat posuere erat, vitae posuere nibh.', 'Galeria3');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `images`
--
ALTER TABLE `images`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `images`
--
ALTER TABLE `images`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=37;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
